apiVersion: v1
kind: Service
metadata:
  name: falkordb
  namespace: guyl
spec:
  selector:
    app: falkordb
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: browser
      port: 3000
      targetPort: 3000